# Generated by Django 3.0.8 on 2020-07-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200718_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='text',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='Url на картинку'),
        ),
    ]
