# Generated by Django 3.0.8 on 2020-07-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200721_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=200, null=True, verbose_name='Url на картинку'),
        ),
    ]
