# Generated by Django 3.0.8 on 2020-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200722_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=200, verbose_name='Url на картинку'),
        ),
    ]
