# Generated by Django 3.0.8 on 2020-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20200726_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default=None, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(default=None, max_length=200, verbose_name='Url на картинку'),
        ),
    ]
